import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { BRAND } from '../config/brand';

const LANGUAGE_KEY = `${BRAND.storagePrefix}language`;

export type Language = 'es' | 'en' | 'pt' | 'fr' | 'it';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Detect browser language
// Only languages the whole site is written in are offered. Most pages exist only
// in Spanish, so the others stay off until those pages are translated; add them
// back here to bring the selector back.
export const ENABLED_LANGUAGES: Language[] = ['es'];

const detectLanguage = (): Language => {
  const saved = localStorage.getItem(LANGUAGE_KEY) as Language;
  if (saved && ENABLED_LANGUAGES.includes(saved)) return saved;
  const browserLang = (navigator.language || '').split('-')[0].toLowerCase() as Language;
  return ENABLED_LANGUAGES.includes(browserLang) ? browserLang : 'es';
};

// Translations
const translations: Record<Language, Record<string, string>> = {
  es: {
    // Navbar
    'nav.explore': 'Explorar',
    'nav.dashboard': 'Panel',
    'nav.admin': 'Admin',
    'nav.profile': 'Mi Perfil',
    'nav.settings': 'Configuración',
    'nav.help': 'Ayuda',
    'nav.logout': 'Cerrar Sesión',
    'nav.login': 'Iniciar Sesión',
    'nav.register': 'Registrarse',
    
    // Landing
    'landing.hero.title1': 'Más cerca de quienes',
    'landing.hero.title2': 'te inspiran',
    'landing.hero.subtitle': 'Membresías, contenido exclusivo, experiencias VIP y sesiones en vivo con creadores que conectan contigo más allá del feed.',
    'landing.hero.cta1': 'Crear cuenta gratis',
    'landing.hero.cta2': 'Explorar creadores',
    'landing.hero.stats1': 'Creadores verificados',
    'landing.hero.stats2': 'Comunidad +18',
    'landing.hero.stats3': 'Pagos protegidos',
    'landing.featured.title': 'Creadores destacados',
    'landing.featured.subtitle': 'Perfiles que su comunidad sigue de cerca',
    'landing.featured.viewAll': 'Ver todos los creadores',
    'landing.categories.title': 'Explora por categorías',
    'landing.categories.subtitle': 'Música, fitness, gaming, arte y mucho más',
    'landing.how.title': '¿Cómo funciona?',
    'landing.how.subtitle': 'Tres pasos para empezar en {brand}',
    'landing.how.step1.title': '1. Crea tu cuenta',
    'landing.how.step1.desc': 'Regístrate gratis y confirma tu edad en un minuto.',
    'landing.how.step2.title': '2. Descubre creadores',
    'landing.how.step2.desc': 'Explora perfiles, encuentra a quienes te inspiran y únete a su membresía.',
    'landing.how.step3.title': '3. Conecta y apoya',
    'landing.how.step3.desc': 'Accede a contenido exclusivo, escribe a tus creadores y apóyalos con propinas y regalos.',
    'landing.cta.title': '¿Creas contenido o experiencias?',
    'landing.cta.subtitle': 'Convierte a tu audiencia en una comunidad que te apoya. En {brand} tú defines tus precios, tus membresías y tus experiencias.',
    'landing.cta.button': 'Empezar como creador',
    
    // Age Verification
    'age.title': 'Verificación de edad',
    'age.description': '{brand} es una comunidad solo para mayores de 18 años. Algunos creadores publican contenido para adultos. Confirma tu edad para continuar.',
    'age.warning': 'Aviso legal',
    'age.warningText': 'Al ingresar, declaras bajo juramento que tienes 18 años o más. El acceso a menores está estrictamente prohibido.',
    'age.confirm': 'Sí, soy mayor de 18 años',
    'age.deny': 'No, soy menor de 18 años',
    'age.denied.title': 'Acceso denegado',
    'age.denied.text': 'Lo sentimos, debes ser mayor de 18 años para acceder a {brand}. Serás redirigido en unos momentos.',
    'age.denied.button': 'Salir del sitio',
    'age.terms': 'Al continuar, aceptas nuestros',
    'age.termsLink': 'Términos de Servicio',
    'age.and': 'y',
    'age.privacyLink': 'Política de Privacidad',
    
    // Login
    'login.title': 'Bienvenido de vuelta',
    'login.subtitle': 'Inicia sesión en tu cuenta',
    'login.email': 'Correo electrónico',
    'login.password': 'Contraseña',
    'login.remember': 'Recordarme',
    'login.forgot': '¿Olvidaste tu contraseña?',
    'login.submit': 'Iniciar Sesión',
    'login.or': 'o continúa con',
    'login.noAccount': '¿No tienes cuenta?',
    'login.register': 'Regístrate gratis',
    'login.demo': 'Demo rápida:',
    'login.demoFan': 'Fan: fan@sugarfans.com / demo1234',
    'login.demoCreator': 'Creador: creator@sugarfans.com / demo1234',
    'login.demoAdmin': 'Admin: admin@sugarfans.com / demo1234',
    
    // Register
    'register.createAccount': 'Crear cuenta',
    'register.security': 'Seguridad',
    'register.accountType': 'Tipo de cuenta',
    'register.basicInfo': 'Ingresa tus datos básicos',
    'register.passwordInfo': 'Crea una contraseña segura',
    'register.howToUse': '¿Cómo quieres usar {brand}?',
    'register.fullName': 'Nombre completo',
    'register.email': 'Correo electrónico',
    'register.password': 'Contraseña',
    'register.confirmPassword': 'Confirmar contraseña',
    'register.continue': 'Continuar',
    'register.back': 'Atrás',
    'register.fan': 'Fan',
    'register.fanDesc': 'Ver y apoyar creadores',
    'register.creator': 'Creador',
    'register.creatorDesc': 'Publicar y monetizar',
    'register.terms': 'Acepto los',
    'register.termsLink': 'Términos de Servicio',
    'register.and': 'la',
    'register.privacyLink': 'Política de Privacidad',
    'register.ageConfirm': 'y confirmo que soy mayor de 18 años.',
    'register.submit': 'Crear Cuenta',
    'register.hasAccount': '¿Ya tienes cuenta?',
    'register.login': 'Inicia sesión',
    
    // Footer
    'footer.description': '{brand} conecta a creadores con sus verdaderos fans: membresías, contenido exclusivo y experiencias VIP.',
    'footer.platform': 'Plataforma',
    'footer.explore': 'Explorar',
    'footer.pricing': 'Ser creador',
    'footer.help': 'Centro de ayuda',
    'footer.becomeCreator': 'Únete como creador',
    'footer.legal': 'Legal',
    'footer.terms': 'Términos de Servicio',
    'footer.privacy': 'Política de Privacidad',
    'footer.cookies': 'Política de Cookies',
    'footer.dmca': 'DMCA',
    'footer.security': 'Seguridad',
    'footer.reportContent': 'Reportar Contenido',
    'footer.minorProtection': 'Protección de Menores',
    'footer.identityVerification': 'Verificación de Identidad',
    'footer.copyright': 'Derechos de Autor',
    'footer.rights': 'Todos los derechos reservados. Solo para mayores de 18 años.',
    
    // Common
    'common.perMonth': '/mes',
    'common.followers': 'Seguidores',
    'common.posts': 'Publicaciones',
    'common.likes': 'Me gusta',
    'common.subscribe': 'Suscribirse',
    'common.subscribed': 'Suscrito',
    'common.unlock': 'Desbloquear',
    'common.exclusiveContent': 'Contenido exclusivo',
    'common.tip': 'Propina',
    'common.share': 'Compartir',
    'common.report': 'Reportar',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.view': 'Ver',
    'common.all': 'Todos',
  },
  
  en: {
    // Navbar
    'nav.explore': 'Explore',
    'nav.dashboard': 'Dashboard',
    'nav.admin': 'Admin',
    'nav.profile': 'My Profile',
    'nav.settings': 'Settings',
    'nav.help': 'Help',
    'nav.logout': 'Log Out',
    'nav.login': 'Log In',
    'nav.register': 'Sign Up',
    
    // Landing
    'landing.hero.title1': 'Connect with your',
    'landing.hero.title2': 'favorite creators',
    'landing.hero.subtitle': 'Discover exclusive content from your favorite creators. Subscribe, support, and enjoy unique experiences.',
    'landing.hero.cta1': 'Start Free',
    'landing.hero.cta2': 'Explore Creators',
    'landing.hero.stats1': 'Verified creators',
    'landing.hero.stats2': 'Adults only (18+)',
    'landing.hero.stats3': 'Secure Payments',
    'landing.featured.title': 'Featured Creators',
    'landing.featured.subtitle': 'Discover the most popular creators on our platform',
    'landing.featured.viewAll': 'View all creators',
    'landing.categories.title': 'Explore by Categories',
    'landing.categories.subtitle': 'Find exactly what you\'re looking for',
    'landing.how.title': 'How does it work?',
    'landing.how.subtitle': 'It\'s easy to get started on {brand}',
    'landing.how.step1.title': '1. Create your account',
    'landing.how.step1.desc': 'Sign up for free and verify your age to access all content.',
    'landing.how.step2.title': '2. Discover creators',
    'landing.how.step2.desc': 'Browse profiles, find your favorite content, and subscribe.',
    'landing.how.step3.title': '3. Enjoy and support',
    'landing.how.step3.desc': 'Access exclusive content, send messages, and support your favorites.',
    'landing.cta.title': 'Are you a content creator?',
    'landing.cta.subtitle': 'Join {brand} and monetize your content. Control your prices, connect with your fans, and grow your community.',
    'landing.cta.button': 'Start as a Creator',
    
    // Age Verification
    'age.title': 'Age Verification',
    'age.description': 'This site contains exclusive adult content. You must confirm that you are over 18 years old to continue.',
    'age.warning': 'Legal Notice',
    'age.warningText': 'By entering, you declare under oath that you are 18 years or older. Access by minors is strictly prohibited.',
    'age.confirm': 'Yes, I am over 18 years old',
    'age.deny': 'No, I am under 18 years old',
    'age.denied.title': 'Access Denied',
    'age.denied.text': 'Sorry, you must be over 18 years old to access {brand}. You will be redirected in a moment.',
    'age.denied.button': 'Exit site',
    'age.terms': 'By continuing, you accept our',
    'age.termsLink': 'Terms of Service',
    'age.and': 'and',
    'age.privacyLink': 'Privacy Policy',
    
    // Login
    'login.title': 'Welcome back',
    'login.subtitle': 'Log in to your account',
    'login.email': 'Email address',
    'login.password': 'Password',
    'login.remember': 'Remember me',
    'login.forgot': 'Forgot your password?',
    'login.submit': 'Log In',
    'login.or': 'or continue with',
    'login.noAccount': 'Don\'t have an account?',
    'login.register': 'Sign up for free',
    'login.demo': 'Quick demo:',
    'login.demoFan': 'Fan: fan@sugarfans.com / demo1234',
    'login.demoCreator': 'Creator: creator@sugarfans.com / demo1234',
    'login.demoAdmin': 'Admin: admin@sugarfans.com / demo1234',
    
    // Register
    'register.createAccount': 'Create account',
    'register.security': 'Security',
    'register.accountType': 'Account type',
    'register.basicInfo': 'Enter your basic information',
    'register.passwordInfo': 'Create a secure password',
    'register.howToUse': 'How do you want to use {brand}?',
    'register.fullName': 'Full name',
    'register.email': 'Email address',
    'register.password': 'Password',
    'register.confirmPassword': 'Confirm password',
    'register.continue': 'Continue',
    'register.back': 'Back',
    'register.fan': 'Fan',
    'register.fanDesc': 'View and support creators',
    'register.creator': 'Creator',
    'register.creatorDesc': 'Publish and monetize',
    'register.terms': 'I accept the',
    'register.termsLink': 'Terms of Service',
    'register.and': 'the',
    'register.privacyLink': 'Privacy Policy',
    'register.ageConfirm': 'and I confirm that I am over 18 years old.',
    'register.submit': 'Create Account',
    'register.hasAccount': 'Already have an account?',
    'register.login': 'Log in',
    
    // Footer
    'footer.description': 'The subscription platform for content creators. Connect with your favorite creators.',
    'footer.platform': 'Platform',
    'footer.explore': 'Explore',
    'footer.pricing': 'Become a creator',
    'footer.help': 'Help Center',
    'footer.becomeCreator': 'Become a Creator',
    'footer.legal': 'Legal',
    'footer.terms': 'Terms of Service',
    'footer.privacy': 'Privacy Policy',
    'footer.cookies': 'Cookie Policy',
    'footer.dmca': 'DMCA',
    'footer.security': 'Security',
    'footer.reportContent': 'Report Content',
    'footer.minorProtection': 'Minor Protection',
    'footer.identityVerification': 'Identity Verification',
    'footer.copyright': 'Copyright',
    'footer.rights': 'All rights reserved. For adults 18+ only.',
    
    // Common
    'common.perMonth': '/month',
    'common.followers': 'Followers',
    'common.posts': 'Posts',
    'common.likes': 'Likes',
    'common.subscribe': 'Subscribe',
    'common.subscribed': 'Subscribed',
    'common.unlock': 'Unlock',
    'common.exclusiveContent': 'Exclusive content',
    'common.tip': 'Tip',
    'common.share': 'Share',
    'common.report': 'Report',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.all': 'All',
  },
  
  pt: {
    // Navbar
    'nav.explore': 'Explorar',
    'nav.dashboard': 'Painel',
    'nav.admin': 'Admin',
    'nav.profile': 'Meu Perfil',
    'nav.settings': 'Configurações',
    'nav.help': 'Ajuda',
    'nav.logout': 'Sair',
    'nav.login': 'Entrar',
    'nav.register': 'Cadastrar',
    
    // Landing
    'landing.hero.title1': 'Conecte-se com seus',
    'landing.hero.title2': 'criadores favoritos',
    'landing.hero.subtitle': 'Descubra conteúdo exclusivo dos seus criadores favoritos. Assine, apoie e desfrute de experiências únicas.',
    'landing.hero.cta1': 'Começar Grátis',
    'landing.hero.cta2': 'Explorar Criadores',
    'landing.hero.stats1': 'Criadores verificados',
    'landing.hero.stats2': 'Apenas maiores de 18',
    'landing.hero.stats3': 'Pagamentos Seguros',
    'landing.featured.title': 'Criadores em Destaque',
    'landing.featured.subtitle': 'Descubra os criadores mais populares da nossa plataforma',
    'landing.featured.viewAll': 'Ver todos os criadores',
    'landing.categories.title': 'Explore por Categorias',
    'landing.categories.subtitle': 'Encontre exatamente o que você procura',
    'landing.how.title': 'Como funciona?',
    'landing.how.subtitle': 'É fácil começar no {brand}',
    'landing.how.step1.title': '1. Crie sua conta',
    'landing.how.step1.desc': 'Cadastre-se grátis e verifique sua idade para acessar todo o conteúdo.',
    'landing.how.step2.title': '2. Descubra criadores',
    'landing.how.step2.desc': 'Explore perfis, encontre seu conteúdo favorito e assine.',
    'landing.how.step3.title': '3. Aproveite e apoie',
    'landing.how.step3.desc': 'Acesse conteúdo exclusivo, envie mensagens e apoie seus favoritos.',
    'landing.cta.title': 'Você é criador de conteúdo?',
    'landing.cta.subtitle': 'Junte-se ao {brand} e monetize seu conteúdo. Controle seus preços, conecte-se com seus fãs e cresça sua comunidade.',
    'landing.cta.button': 'Começar como Criador',
    
    // Age Verification
    'age.title': 'Verificação de Idade',
    'age.description': 'Este site contém conteúdo exclusivo para adultos. Você deve confirmar que tem mais de 18 anos para continuar.',
    'age.warning': 'Aviso Legal',
    'age.warningText': 'Ao entrar, você declara sob juramento que tem 18 anos ou mais. O acesso de menores é estritamente proibido.',
    'age.confirm': 'Sim, tenho mais de 18 anos',
    'age.deny': 'Não, tenho menos de 18 anos',
    'age.denied.title': 'Acesso Negado',
    'age.denied.text': 'Desculpe, você deve ter mais de 18 anos para acessar o {brand}. Você será redirecionado em um momento.',
    'age.denied.button': 'Sair do site',
    'age.terms': 'Ao continuar, você aceita nossos',
    'age.termsLink': 'Termos de Serviço',
    'age.and': 'e',
    'age.privacyLink': 'Política de Privacidade',
    
    // Login
    'login.title': 'Bem-vindo de volta',
    'login.subtitle': 'Entre na sua conta',
    'login.email': 'Endereço de email',
    'login.password': 'Senha',
    'login.remember': 'Lembrar-me',
    'login.forgot': 'Esqueceu sua senha?',
    'login.submit': 'Entrar',
    'login.or': 'ou continue com',
    'login.noAccount': 'Não tem conta?',
    'login.register': 'Cadastre-se grátis',
    'login.demo': 'Demo rápida:',
    'login.demoFan': 'Fan: fan@sugarfans.com / demo1234',
    'login.demoCreator': 'Criador: creator@sugarfans.com / demo1234',
    'login.demoAdmin': 'Admin: admin@sugarfans.com / demo1234',
    
    // Register
    'register.createAccount': 'Criar conta',
    'register.security': 'Segurança',
    'register.accountType': 'Tipo de conta',
    'register.basicInfo': 'Insira seus dados básicos',
    'register.passwordInfo': 'Crie uma senha segura',
    'register.howToUse': 'Como você quer usar o {brand}?',
    'register.fullName': 'Nome completo',
    'register.email': 'Endereço de email',
    'register.password': 'Senha',
    'register.confirmPassword': 'Confirmar senha',
    'register.continue': 'Continuar',
    'register.back': 'Voltar',
    'register.fan': 'Fã',
    'register.fanDesc': 'Ver e apoiar criadores',
    'register.creator': 'Criador',
    'register.creatorDesc': 'Publicar e monetizar',
    'register.terms': 'Aceito os',
    'register.termsLink': 'Termos de Serviço',
    'register.and': 'a',
    'register.privacyLink': 'Política de Privacidade',
    'register.ageConfirm': 'e confirmo que tenho mais de 18 anos.',
    'register.submit': 'Criar Conta',
    'register.hasAccount': 'Já tem conta?',
    'register.login': 'Entre',
    
    // Footer
    'footer.description': 'A plataforma de assinaturas para criadores de conteúdo. Conecte-se com seus criadores favoritos.',
    'footer.platform': 'Plataforma',
    'footer.explore': 'Explorar',
    'footer.pricing': 'Seja criador',
    'footer.help': 'Central de Ajuda',
    'footer.becomeCreator': 'Seja um Criador',
    'footer.legal': 'Legal',
    'footer.terms': 'Termos de Serviço',
    'footer.privacy': 'Política de Privacidade',
    'footer.cookies': 'Política de Cookies',
    'footer.dmca': 'DMCA',
    'footer.security': 'Segurança',
    'footer.reportContent': 'Reportar Conteúdo',
    'footer.minorProtection': 'Proteção de Menores',
    'footer.identityVerification': 'Verificação de Identidade',
    'footer.copyright': 'Direitos Autorais',
    'footer.rights': 'Todos os direitos reservados. Apenas para maiores de 18 anos.',
    
    // Common
    'common.perMonth': '/mês',
    'common.followers': 'Seguidores',
    'common.posts': 'Publicações',
    'common.likes': 'Curtidas',
    'common.subscribe': 'Assinar',
    'common.subscribed': 'Assinado',
    'common.unlock': 'Desbloquear',
    'common.exclusiveContent': 'Conteúdo exclusivo',
    'common.tip': 'Gorjeta',
    'common.share': 'Compartilhar',
    'common.report': 'Reportar',
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Excluir',
    'common.edit': 'Editar',
    'common.view': 'Ver',
    'common.all': 'Todos',
  },
  
  fr: {
    // Navbar
    'nav.explore': 'Explorer',
    'nav.dashboard': 'Tableau de bord',
    'nav.admin': 'Admin',
    'nav.profile': 'Mon Profil',
    'nav.settings': 'Paramètres',
    'nav.help': 'Aide',
    'nav.logout': 'Déconnexion',
    'nav.login': 'Connexion',
    'nav.register': 'S\'inscrire',
    
    // Landing
    'landing.hero.title1': 'Connectez-vous avec vos',
    'landing.hero.title2': 'créateurs favoris',
    'landing.hero.subtitle': 'Découvrez du contenu exclusif de vos créateurs préférés. Abonnez-vous, soutenez et profitez d\'expériences uniques.',
    'landing.hero.cta1': 'Commencer Gratuitement',
    'landing.hero.cta2': 'Explorer les Créateurs',
    'landing.hero.stats1': 'Créateurs vérifiés',
    'landing.hero.stats2': 'Réservé aux 18 ans et plus',
    'landing.hero.stats3': 'Paiements Sécurisés',
    'landing.featured.title': 'Créateurs en Vedette',
    'landing.featured.subtitle': 'Découvrez les créateurs les plus populaires de notre plateforme',
    'landing.featured.viewAll': 'Voir tous les créateurs',
    'landing.categories.title': 'Explorer par Catégories',
    'landing.categories.subtitle': 'Trouvez exactement ce que vous cherchez',
    'landing.how.title': 'Comment ça marche?',
    'landing.how.subtitle': 'C\'est facile de commencer sur {brand}',
    'landing.how.step1.title': '1. Créez votre compte',
    'landing.how.step1.desc': 'Inscrivez-vous gratuitement et vérifiez votre âge pour accéder à tout le contenu.',
    'landing.how.step2.title': '2. Découvrez les créateurs',
    'landing.how.step2.desc': 'Parcourez les profils, trouvez votre contenu préféré et abonnez-vous.',
    'landing.how.step3.title': '3. Profitez et soutenez',
    'landing.how.step3.desc': 'Accédez au contenu exclusif, envoyez des messages et soutenez vos favoris.',
    'landing.cta.title': 'Êtes-vous créateur de contenu?',
    'landing.cta.subtitle': 'Rejoignez {brand} et monétisez votre contenu. Contrôlez vos prix, connectez-vous avec vos fans et développez votre communauté.',
    'landing.cta.button': 'Commencer en tant que Créateur',
    
    // Age Verification
    'age.title': 'Vérification de l\'Âge',
    'age.description': 'Ce site contient du contenu exclusif pour adultes. Vous devez confirmer que vous avez plus de 18 ans pour continuer.',
    'age.warning': 'Avis Légal',
    'age.warningText': 'En entrant, vous déclarez sous serment que vous avez 18 ans ou plus. L\'accès aux mineurs est strictement interdit.',
    'age.confirm': 'Oui, j\'ai plus de 18 ans',
    'age.deny': 'Non, j\'ai moins de 18 ans',
    'age.denied.title': 'Accès Refusé',
    'age.denied.text': 'Désolé, vous devez avoir plus de 18 ans pour accéder à {brand}. Vous serez redirigé dans un instant.',
    'age.denied.button': 'Quitter le site',
    'age.terms': 'En continuant, vous acceptez nos',
    'age.termsLink': 'Conditions d\'Utilisation',
    'age.and': 'et',
    'age.privacyLink': 'Politique de Confidentialité',
    
    // Login
    'login.title': 'Bienvenue',
    'login.subtitle': 'Connectez-vous à votre compte',
    'login.email': 'Adresse email',
    'login.password': 'Mot de passe',
    'login.remember': 'Se souvenir de moi',
    'login.forgot': 'Mot de passe oublié?',
    'login.submit': 'Connexion',
    'login.or': 'ou continuer avec',
    'login.noAccount': 'Vous n\'avez pas de compte?',
    'login.register': 'Inscrivez-vous gratuitement',
    'login.demo': 'Démo rapide:',
    'login.demoFan': 'Fan: fan@sugarfans.com / demo1234',
    'login.demoCreator': 'Créateur: creator@sugarfans.com / demo1234',
    'login.demoAdmin': 'Admin: admin@sugarfans.com / demo1234',
    
    // Register
    'register.createAccount': 'Créer un compte',
    'register.security': 'Sécurité',
    'register.accountType': 'Type de compte',
    'register.basicInfo': 'Entrez vos informations de base',
    'register.passwordInfo': 'Créez un mot de passe sécurisé',
    'register.howToUse': 'Comment voulez-vous utiliser {brand}?',
    'register.fullName': 'Nom complet',
    'register.email': 'Adresse email',
    'register.password': 'Mot de passe',
    'register.confirmPassword': 'Confirmer le mot de passe',
    'register.continue': 'Continuer',
    'register.back': 'Retour',
    'register.fan': 'Fan',
    'register.fanDesc': 'Voir et soutenir les créateurs',
    'register.creator': 'Créateur',
    'register.creatorDesc': 'Publier et monétiser',
    'register.terms': 'J\'accepte les',
    'register.termsLink': 'Conditions d\'Utilisation',
    'register.and': 'la',
    'register.privacyLink': 'Politique de Confidentialité',
    'register.ageConfirm': 'et je confirme que j\'ai plus de 18 ans.',
    'register.submit': 'Créer le Compte',
    'register.hasAccount': 'Vous avez déjà un compte?',
    'register.login': 'Connectez-vous',
    
    // Footer
    'footer.description': 'La plateforme d\'abonnement pour les créateurs de contenu. Connectez-vous avec vos créateurs favoris.',
    'footer.platform': 'Plateforme',
    'footer.explore': 'Explorer',
    'footer.pricing': 'Devenir créateur',
    'footer.help': 'Centre d\'Aide',
    'footer.becomeCreator': 'Devenir Créateur',
    'footer.legal': 'Légal',
    'footer.terms': 'Conditions d\'Utilisation',
    'footer.privacy': 'Politique de Confidentialité',
    'footer.cookies': 'Politique de Cookies',
    'footer.dmca': 'DMCA',
    'footer.security': 'Sécurité',
    'footer.reportContent': 'Signaler du Contenu',
    'footer.minorProtection': 'Protection des Mineurs',
    'footer.identityVerification': 'Vérification d\'Identité',
    'footer.copyright': 'Droits d\'Auteur',
    'footer.rights': 'Tous droits réservés. Réservé aux adultes de 18 ans et plus.',
    
    // Common
    'common.perMonth': '/mois',
    'common.followers': 'Abonnés',
    'common.posts': 'Publications',
    'common.likes': 'J\'aime',
    'common.subscribe': 'S\'abonner',
    'common.subscribed': 'Abonné',
    'common.unlock': 'Débloquer',
    'common.exclusiveContent': 'Contenu exclusif',
    'common.tip': 'Pourboire',
    'common.share': 'Partager',
    'common.report': 'Signaler',
    'common.save': 'Sauvegarder',
    'common.cancel': 'Annuler',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.view': 'Voir',
    'common.all': 'Tous',
  },
  
  it: {
    // Navbar
    'nav.explore': 'Esplora',
    'nav.dashboard': 'Pannello',
    'nav.admin': 'Admin',
    'nav.profile': 'Il Mio Profilo',
    'nav.settings': 'Impostazioni',
    'nav.help': 'Aiuto',
    'nav.logout': 'Esci',
    'nav.login': 'Accedi',
    'nav.register': 'Registrati',
    
    // Landing
    'landing.hero.title1': 'Connettiti con i tuoi',
    'landing.hero.title2': 'creatori preferiti',
    'landing.hero.subtitle': 'Scopri contenuti esclusivi dai tuoi creatori preferiti. Iscriviti, supporta e goditi esperienze uniche.',
    'landing.hero.cta1': 'Inizia Gratis',
    'landing.hero.cta2': 'Esplora Creatori',
    'landing.hero.stats1': 'Creatori verificati',
    'landing.hero.stats2': 'Solo maggiorenni',
    'landing.hero.stats3': 'Pagamenti Sicuri',
    'landing.featured.title': 'Creatori in Evidenza',
    'landing.featured.subtitle': 'Scopri i creatori più popolari sulla nostra piattaforma',
    'landing.featured.viewAll': 'Vedi tutti i creatori',
    'landing.categories.title': 'Esplora per Categorie',
    'landing.categories.subtitle': 'Trova esattamente ciò che cerchi',
    'landing.how.title': 'Come funziona?',
    'landing.how.subtitle': 'È facile iniziare su {brand}',
    'landing.how.step1.title': '1. Crea il tuo account',
    'landing.how.step1.desc': 'Registrati gratuitamente e verifica la tua età per accedere a tutti i contenuti.',
    'landing.how.step2.title': '2. Scopri i creatori',
    'landing.how.step2.desc': 'Sfoglia i profili, trova i tuoi contenuti preferiti e iscriviti.',
    'landing.how.step3.title': '3. Goditi e supporta',
    'landing.how.step3.desc': 'Accedi a contenuti esclusivi, invia messaggi e supporta i tuoi preferiti.',
    'landing.cta.title': 'Sei un creatore di contenuti?',
    'landing.cta.subtitle': 'Unisciti a {brand} e monetizza i tuoi contenuti. Controlla i tuoi prezzi, connettiti con i tuoi fan e fai crescere la tua community.',
    'landing.cta.button': 'Inizia come Creatore',
    
    // Age Verification
    'age.title': 'Verifica dell\'Età',
    'age.description': 'Questo sito contiene contenuti esclusivi per adulti. Devi confermare di avere più di 18 anni per continuare.',
    'age.warning': 'Avviso Legale',
    'age.warningText': 'Entrando, dichiari sotto giuramento di avere 18 anni o più. L\'accesso ai minori è severamente vietato.',
    'age.confirm': 'Sì, ho più di 18 anni',
    'age.deny': 'No, ho meno di 18 anni',
    'age.denied.title': 'Accesso Negato',
    'age.denied.text': 'Spiacenti, devi avere più di 18 anni per accedere a {brand}. Sarai reindirizzato tra un momento.',
    'age.denied.button': 'Esci dal sito',
    'age.terms': 'Continuando, accetti i nostri',
    'age.termsLink': 'Termini di Servizio',
    'age.and': 'e',
    'age.privacyLink': 'Informativa sulla Privacy',
    
    // Login
    'login.title': 'Bentornato',
    'login.subtitle': 'Accedi al tuo account',
    'login.email': 'Indirizzo email',
    'login.password': 'Password',
    'login.remember': 'Ricordami',
    'login.forgot': 'Password dimenticata?',
    'login.submit': 'Accedi',
    'login.or': 'o continua con',
    'login.noAccount': 'Non hai un account?',
    'login.register': 'Registrati gratuitamente',
    'login.demo': 'Demo veloce:',
    'login.demoFan': 'Fan: fan@sugarfans.com / demo1234',
    'login.demoCreator': 'Creatore: creator@sugarfans.com / demo1234',
    'login.demoAdmin': 'Admin: admin@sugarfans.com / demo1234',
    
    // Register
    'register.createAccount': 'Crea account',
    'register.security': 'Sicurezza',
    'register.accountType': 'Tipo di account',
    'register.basicInfo': 'Inserisci le tue informazioni di base',
    'register.passwordInfo': 'Crea una password sicura',
    'register.howToUse': 'Come vuoi usare {brand}?',
    'register.fullName': 'Nome completo',
    'register.email': 'Indirizzo email',
    'register.password': 'Password',
    'register.confirmPassword': 'Conferma password',
    'register.continue': 'Continua',
    'register.back': 'Indietro',
    'register.fan': 'Fan',
    'register.fanDesc': 'Vedi e supporta creatori',
    'register.creator': 'Creatore',
    'register.creatorDesc': 'Pubblica e monetizza',
    'register.terms': 'Accetto i',
    'register.termsLink': 'Termini di Servizio',
    'register.and': 'l\'',
    'register.privacyLink': 'Informativa sulla Privacy',
    'register.ageConfirm': 'e confermo di avere più di 18 anni.',
    'register.submit': 'Crea Account',
    'register.hasAccount': 'Hai già un account?',
    'register.login': 'Accedi',
    
    // Footer
    'footer.description': 'La piattaforma di abbonamento per creatori di contenuti. Connettiti con i tuoi creatori preferiti.',
    'footer.platform': 'Piattaforma',
    'footer.explore': 'Esplora',
    'footer.pricing': 'Diventa creatore',
    'footer.help': 'Centro Assistenza',
    'footer.becomeCreator': 'Diventa Creatore',
    'footer.legal': 'Legale',
    'footer.terms': 'Termini di Servizio',
    'footer.privacy': 'Informativa sulla Privacy',
    'footer.cookies': 'Politica dei Cookie',
    'footer.dmca': 'DMCA',
    'footer.security': 'Sicurezza',
    'footer.reportContent': 'Segnala Contenuto',
    'footer.minorProtection': 'Protezione dei Minori',
    'footer.identityVerification': 'Verifica dell\'Identità',
    'footer.copyright': 'Diritti d\'Autore',
    'footer.rights': 'Tutti i diritti riservati. Solo per adulti di 18 anni o più.',
    
    // Common
    'common.perMonth': '/mese',
    'common.followers': 'Follower',
    'common.posts': 'Pubblicazioni',
    'common.likes': 'Mi piace',
    'common.subscribe': 'Iscriviti',
    'common.subscribed': 'Iscritto',
    'common.unlock': 'Sblocca',
    'common.exclusiveContent': 'Contenuto esclusivo',
    'common.tip': 'Mancia',
    'common.share': 'Condividi',
    'common.report': 'Segnala',
    'common.save': 'Salva',
    'common.cancel': 'Annulla',
    'common.delete': 'Elimina',
    'common.edit': 'Modifica',
    'common.view': 'Visualizza',
    'common.all': 'Tutti',
  },
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(detectLanguage());

  useEffect(() => {
    localStorage.setItem(LANGUAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    const text = translations[language][key] || key;
    return text.replace(/\{brand\}/g, BRAND.name);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};

export const languageNames: Record<Language, string> = {
  es: 'Español',
  en: 'English',
  pt: 'Português',
  fr: 'Français',
  it: 'Italiano',
};
